[package]
name = "rssg"
version = "1.0.0"
edition = "2021"

license = "mit"
authors = ["Kyllingene"]

[dependencies]
regex = "1.7"
serde = "1.0"
toml = "0.7"
serde_yaml = "0.9"
yaml-front-matter = "0.1.0"
