[filters]

[filters.asciidoc]
command = "asciidoctor --no-header-footer {full} -o {outfile}"
outfile = "{dir}/{name}/index.html"

[rules]

[rules.".*index.html"]
filters = []
templates = []
output = "{dir}/index.html"

[rules.".*html"]
filters = []
templates = []
output = "{dir}/{name}/index.html"

[rules.".*index.(adoc|asciidoc)"]
filters = ["asciidoc"]
templates = ["default.html"]
output = "{dir}/{name}.html"

[rules.".*(adoc|asciidoc)"]
filters = ["asciidoc"]
templates = ["default.html"]
output = "{dir}/{name}/index.html"

[rules.".*(md|markdown)"]
filters = [{ command = "pandoc {full} -o {outfile}", outfile = "{dir}/{name}/index.html" }]
templates = ["default.html"]
output = "{dir}/{name}/index.html"